### ISSUE TITLE
Two group by?

### ISSUE THREAD

**Issue by sen1** [ashonk/sql-scratch-capstone-turn-in#2]
https://github.com/ashonk/sql-scratch-capstone-turn-in/blob/d6d49ef6e0ed6d7300b3ccb66b082b9adfe9e1fe/File%20for%20Upload/code.sql#L144-L162

The table `status_aggregate` already is group by month. So there is no point of grouping again in the second query.

**Comment by ashonk** [comment]
Yeah, I noticed that, too, but it worked; so I left it. I should have made it tighter.
