### ISSUE TITLE
Rubric score

### ISSUE THREAD

**Issue by sen1** [ashonk/sql-scratch-capstone-turn-in#3]
### Criteria 1: Report: Are conclusions clear and supported by evidence in all eight answers?
* 4 (Exceeds Expectations) 
* You got it.
 
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* 4 (Exceeds Expectations) 
* Results were expected. Nice job.
 
### Criteria 3: Query Formatting
* 3 (Meets Expectations)
* Made few comments on the other issue. Queries can be better formatted.
 
### Criteria 4: Understanding the underlying concepts and terminology
* 4 (Exceeds Expectations)
* Good job.

 ### Overall Score: 15/16
Excellent work. 👏

**Comment by ashonk** [comment]
Thanks.
